### ISSUE TITLE
Mumble - rounded Box

### ISSUE THREAD

**Issue by webrooster** [smartive-education/design-system-component-library-yeahyeahyeah#53]
Situation: Mumble "Timeline" hat keine "runde Ecken" für die Page "Timeline"
Ergänzung: Image muss optional sein

![image](https://user-images.githubusercontent.com/1950432/210955110-37969bee-2f42-404e-ab6c-3d6eeb445277.png)

**Comment by tomschall** [comment]
Image muss optional sein
